package com.web.prova.Entidade;
// Generated 30/11/2018 01:26:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Extrato generated by hbm2java
 */
public class Extrato  implements java.io.Serializable {


     private Integer id;
     private String cpfUser;
     private Double valor;
     private String tipo;
     private String beneficiado;
     private Date data;

    public Extrato() {
    }

    public Extrato(String cpfUser, Double valor, String tipo, String beneficiado, Date data) {
       this.cpfUser = cpfUser;
       this.valor = valor;
       this.tipo = tipo;
       this.beneficiado = beneficiado;
       this.data = data;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCpfUser() {
        return this.cpfUser;
    }
    
    public void setCpfUser(String cpfUser) {
        this.cpfUser = cpfUser;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getBeneficiado() {
        return this.beneficiado;
    }
    
    public void setBeneficiado(String beneficiado) {
        this.beneficiado = beneficiado;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


